name: server_side
description: A server app using the shelf package and Docker.
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.3.0
  shelf: ^1.4.0
  shelf_open_api: ^1.0.0
  shelf_router: ^1.1.0
  shelf_static: ^1.1.2
  shelf_swagger_ui: ^1.0.0+2

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.21.0
  shelf_router_generator: ^1.0.6
  build_runner: ^2.4.6
  shelf_open_api_generator: ^1.0.0
